### ISSUE TITLE
rngd daemon load cpu for 100%

### ISSUE THREAD

**Issue by alexsalex** [pikvm/pikvm#190]
Subj.

Cant reproduce this issue, the issue come after disable daemon and enable daemon again.

I found some information about this issue om Arch Linux forums, but its related for older kernel.

RasPi Zero W

![Screen Shot 2021-02-14 at 12 01 13 PM](https://user-images.githubusercontent.com/17325366/107887662-86d5d600-6ebc-11eb-95d2-0dc9ebf2c3d5.png)

**Comment by alexsalex** [comment]
After reboot issue came back...

![Screen Shot 2021-02-14 at 1 12 57 PM](https://user-images.githubusercontent.com/17325366/107889321-935f2c00-6ec6-11eb-8524-f0fa0b5413ef.png)

**Comment by mdevaev** [comment]
What about `systemctl disable rngd`?

**Comment by alexsalex** [comment]
what about it? It works, disable the daemon and the load go to normal... Do I need this daemon?

**Comment by mdevaev** [comment]
This is random number generation and it speeds up handshake https a bit. I think you can turn it off, since there are problems with it. It wasn't there before. RedHat seems to have broken everything.

**Comment by th3drk0ne** [comment]
switch rngd service to the hardware number generator instead of jitter which uses the cpu. 
All raspberry pi models have hardware number generators including the zero. 
Entropy pool will be 3000+ immediately after boot instead of slowly generating the pool using the cpu on boot
[https://blog.thewatertower.org/2019/05/13/randomness-on-raspberry-pi/]



mkdir /etc/systemd/system/rngd.service.d
cat > /etc/systemd/system/rngd.service.d/params.conf <<EOF
# disable jitter source
[Service]
ExecStart=
ExecStart=/sbin/rngd --foreground --debug --exclude 5
EOF
systemctl daemon-reload
systemctl restart rng



@mdevaev could this be added by default to the pi zero build working cleanly on my setup for weeks with a custom ssl with no performance impact

**Comment by mdevaev** [comment]
In case of arch it will be enough to edit `/etc/conf.d/rngd` and append option `-x 5`.

**Comment by mdevaev** [comment]
Done

**Comment by th3drk0ne** [comment]
.

**Comment by wnark** [comment]
Hello, this problem may still exist in the new version of the mirror
![image](https://user-images.githubusercontent.com/24355466/122928745-bcc02500-d39c-11eb-8ec8-b34cd5c5e64d.png)

**Comment by wnark** [comment]
I use
systemctl disable rngd
systemctl stop rngd
Come to stop rngd, don't know what will happen.

**Comment by wnark** [comment]
![image](https://user-images.githubusercontent.com/24355466/122929602-ba11ff80-d39d-11eb-8370-2d899b599cc7.png)
I turned off rgnd, but it still seems to be able to generate random numbers somewhere, rngtest is normal, so pikvm can systemctl disable rngd

**Comment by mdevaev** [comment]
`echo 'RNGD_OPTS="-o /dev/random -r /dev/hwrng -x jitter -x pkcs11 -x rtlsdr"' > /etc/conf.d/rngd` and reboot
